printing
print

	Transcript show: level.
	Transcript cr.
	
	Transcript show: ac.
	Transcript cr.
	
	Transcript show: name.
	Transcript cr.
	
	Transcript show: clazz.
	Transcript cr.	
	
	Transcript show: race.
	Transcript cr.

	Transcript show: str.
	Transcript cr.
	
	Transcript show: const.
	Transcript cr.
	
	Transcript show: wis.
	Transcript cr.
	
	Transcript show: int.
	Transcript cr.
	
	Transcript show: dex.
	Transcript cr.
	
	Transcript show: chr.
	Transcript cr.
	
	Transcript cr.